Update VKSC layers to API v1.0.12
KhronosGroup/VulkanSC-ValidationLayers pull request #9
Opened 2023-01-28 00:04 UTC by sricker-nvidia

Change updates layer scripts to sync the v1.0.12 Vulkan SC headers and makes the necessary updates to build against them.

2023-01-28 00:29 UTC, sricker-nvidia commented
Forgot to regenerate generated code. Ignore this patch.

2023-01-30 18:52 UTC, dgkoch requested changes

2023-01-30 18:52 UTC, dgkoch commented on scripts/known_good.json
> +          "-DVULKANSC=TRUE"
```suggestion
          "-DVULKANSC=ON"
```

2023-01-31 04:46 UTC, dgkoch approved these changes
LGTM

2023-01-31 06:27 UTC, merged